Update ruby-install to 0.5.0

diff --git a/.local/bin/ruby-install b/.local/bin/ruby-install
--- a/.local/bin/ruby-install
+++ b/.local/bin/ruby-install
@@ -31,7 +31,10 @@ if [[ ! $no_verify -eq 1 ]]; then
 	verify_ruby || fail "Verification of of $ruby_archive failed!"
 fi
 
-extract_ruby   || fail "Unpacking of $ruby_archive failed!"
+if [[ ! $no_extract -eq 1 ]]; then
+  extract_ruby   || fail "Unpacking of $ruby_archive failed!"
+fi
+
 download_patches || fail "Fetching patches $patches failed!"
 apply_patches  || fail "Patching $ruby $ruby_version failed!"
 cd "$src_dir/$ruby_src_dir"
@@ -40,5 +43,9 @@ clean_ruby     || fail "Cleaning $ruby $ruby_version failed!"
 compile_ruby   || fail "Compiling $ruby $ruby_version failed!"
 install_ruby   || fail "Installation of $ruby $ruby_version failed!"
 post_install   || fail "Post-install tasks failed!"
+
+if [[ $cleanup -eq 1 ]]; then
+	cleanup_source  || fail "Cleanup of archive and unpacked source in $src_dir/ failed!"
+fi
 
 log "Successfully installed $ruby $ruby_version into $install_dir"
